# Dart/Flutter static analysis configuration for Health Flare.
#
# Extends the flutter_lints baseline and adds stricter rules aligned with
# docs/features/developer-experience.feature.
#
# Rule documentation: https://dart.dev/lints

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat these as errors so the pipeline fails, not just warns.
    avoid_dynamic_calls: error
    cancel_subscriptions: error
    close_sinks: error
    unawaited_futures: error

  exclude:
    # Exclude generated files from analysis.
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "scripts/**"

linter:
  rules:
    # ── Correctness ──────────────────────────────────────────────────────────

    # Require every future to be awaited or explicitly unawaited().
    # Prevents silent fire-and-forget async bugs.
    unawaited_futures: true

    # Disallow dynamic method calls — forces proper typing.
    avoid_dynamic_calls: true

    # Require stream subscriptions to be cancelled in dispose().
    cancel_subscriptions: true

    # Require sinks to be closed.
    close_sinks: true

    # No print() calls in production code — use a logger instead.
    avoid_print: true

    # ── Style & consistency ───────────────────────────────────────────────────

    # Use package: imports everywhere — no relative imports in lib/.
    always_use_package_imports: true

    # Single quotes for strings (except where the string contains a single quote).
    prefer_single_quotes: true

    # Trailing commas on multi-line argument/parameter lists — improves diffs.
    require_trailing_commas: true

    # Replace unnecessary lambdas with tear-offs.
    unnecessary_lambdas: true

    # ── Declarations ─────────────────────────────────────────────────────────

    # All public API members must have doc comments.
    public_member_api_docs: false  # Aspirational — enable when coverage improves.

    # Prefer const constructors wherever possible.
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # ── Null safety ───────────────────────────────────────────────────────────

    # Prefer using ?? and ?. over explicit null checks where idiomatic.
    prefer_null_aware_operators: true
