name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

# Flutter version pinned here — update in one place when upgrading.
env:
  FLUTTER_VERSION: "3.41.1"

jobs:
  # ── 1. Dependencies ─────────────────────────────────────────────────────────
  flutter-pub-get:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        run: |
          git clone --depth 1 --branch $FLUTTER_VERSION \
            https://github.com/flutter/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: flutter pub get
      - name: Check for discontinued packages
        run: |
          if flutter pub outdated 2>&1 | grep -q "(discontinued)"; then
            echo "❌ One or more dependencies are discontinued. Run 'flutter pub outdated'."
            exit 1
          fi

  # ── 2. Security audit ───────────────────────────────────────────────────────
  flutter-pub-audit:
    name: Security audit
    runs-on: ubuntu-latest
    needs: flutter-pub-get
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        run: |
          git clone --depth 1 --branch $FLUTTER_VERSION \
            https://github.com/flutter/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
      - name: Audit for known vulnerabilities
        run: flutter pub audit

  # ── 3. URL / offline scan ────────────────────────────────────────────────────
  url-scan:
    name: Offline integrity scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for hardcoded URLs in Dart source
        run: bash scripts/check_urls.sh
      - name: Verify google_fonts is not a dependency
        run: |
          if grep -q "google_fonts" pubspec.yaml; then
            echo "❌ google_fonts found in pubspec.yaml — all fonts must be bundled as assets."
            exit 1
          fi
      - name: Verify no google_fonts imports in lib/
        run: |
          if grep -rl "package:google_fonts" lib/; then
            echo "❌ google_fonts import found in lib/. Remove it — fonts are bundled."
            exit 1
          fi

  # ── 4. Formatting ────────────────────────────────────────────────────────────
  dart-format:
    name: Formatting
    runs-on: ubuntu-latest
    needs: flutter-pub-get
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        run: |
          git clone --depth 1 --branch $FLUTTER_VERSION \
            https://github.com/flutter/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
      - name: Check dart format
        run: dart format --output=none --set-exit-if-changed lib/ test/

  # ── 5. Static analysis ───────────────────────────────────────────────────────
  flutter-analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    needs: flutter-pub-get
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        run: |
          git clone --depth 1 --branch $FLUTTER_VERSION \
            https://github.com/flutter/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
      - name: Analyse
        run: flutter analyze --fatal-infos

  # ── 6. Build ─────────────────────────────────────────────────────────────────
  flutter-build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    needs: [flutter-analyze, dart-format, url-scan, flutter-pub-audit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Install Flutter
        run: |
          git clone --depth 1 --branch $FLUTTER_VERSION \
            https://github.com/flutter/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
      - name: Build debug APK
        run: flutter build apk --debug
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7

  # ── 7. Weekly dependency report (scheduled) ──────────────────────────────────
  dependency-audit:
    name: Weekly dependency report
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        run: |
          git clone --depth 1 --branch $FLUTTER_VERSION \
            https://github.com/flutter/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
      - run: flutter pub get
      - name: Report outdated packages
        run: bash scripts/check_deps.sh
