// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by bdd_widget_test from onboarding.feature
//
// To regenerate, run: flutter pub run build_runner build

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:isar_community/isar.dart';

import 'package:health_flare/main.dart';
import 'package:health_flare/core/providers/database_provider.dart';
import 'package:health_flare/core/providers/onboarding_provider.dart';

import '../helpers/test_database.dart';
import 'steps/common_steps.dart';
import 'steps/onboarding_steps.dart';

void main() {
  late Isar isar;

  setUpAll(() async {
    isar = await TestDatabase.open();
    TestContext.isar = isar;
  });

  tearDownAll(() async {
    await TestDatabase.closeAll();
  });

  setUp(() async {
    await TestContext.reset();
  });

  group('Feature: Onboarding', () {
    group('Scenario: Onboarding is shown on first launch when no profiles exist', () {
      testWidgets('shows onboarding screen', (tester) async {
        // Given the app has been installed and launched for the first time
        await givenTheAppHasBeenInstalledAndLaunchedForTheFirstTime(tester);

        // And no profiles exist on this device
        await givenNoProfilesExistOnThisDevice(tester);

        // When the app loads
        await tester.pumpWidget(
          ProviderScope(
            overrides: [isarProvider.overrideWithValue(isar)],
            child: const HealthFlareApp(),
          ),
        );
        await whenTheAppLoads(tester);

        // Then I am shown the top of the onboarding screen
        await thenIAmShownTheOnboardingScreen(tester);
      });
    });

    group('Scenario: CTA button is disabled when name field is empty', () {
      testWidgets('CTA button starts disabled', (tester) async {
        await tester.pumpWidget(
          ProviderScope(
            overrides: [isarProvider.overrideWithValue(isar)],
            child: const HealthFlareApp(),
          ),
        );
        await tester.pumpAndSettle();

        // Then the primary action button is disabled
        await thenThePrimaryButtonIsDisabled(tester);
      });
    });

    group('Scenario: CTA button enables once a name is entered', () {
      testWidgets('CTA button enables after entering name', (tester) async {
        await tester.pumpWidget(
          ProviderScope(
            overrides: [isarProvider.overrideWithValue(isar)],
            child: const HealthFlareApp(),
          ),
        );
        await tester.pumpAndSettle();

        // When I enter "Sarah" in the name field
        await whenIEnterName(tester, 'Sarah');

        // Then the primary action button is enabled
        await thenThePrimaryButtonIsEnabled(tester);
      });
    });

    group('Scenario: Skips onboarding when already complete', () {
      testWidgets('goes to dashboard when onboarding is done', (tester) async {
        await tester.pumpWidget(
          ProviderScope(
            overrides: [
              isarProvider.overrideWithValue(isar),
              onboardingProvider.overrideWith(() {
                final notifier = OnboardingNotifier();
                return notifier..markAlreadyComplete();
              }),
            ],
            child: const HealthFlareApp(),
          ),
        );
        await tester.pumpAndSettle();

        // Should land on the dashboard, not onboarding
        expect(find.text('Health Flare'), findsWidgets);
        expect(find.text('Your health story,\nin your hands.'), findsNothing);
      });
    });
  });
}
